localstack:
  image: localstack/localstack
  ports:
    - "4566:4566"
    - "4572:4572" # s3
  environment:
    - SERVICES=s3
    - DEFAULT_REGION=us-east-1
    - AWS_DEFAULT_REGION=us-east-1
    - HOSTNAME_EXTERNAL=localhost
    - USE_SSL=false
    - DATA_DIR=/tmp/localstack/data
    - DEBUG=1
    - EXTRA_CORS_ALLOWED_ORIGINS=app://.
  volumes:
    - "/tmp/localstack:/tmp/localstack"
    - ./.aws:/docker-entrypoint-initaws.d
